name: Build and push  Docker Image

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.DEVOPS3_TOKEN }}

      - name: Build Docker Image
        run: docker build --no-cache -t ghcr.io/${{ github.repository }}/my-nginx:$VERSION .

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/${{ github.repository }}/my-nginx:$VERSION

