name: CI/CD for Nginx Deployment

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          file: ./path/to/Dockerfile
          push: true
          tags: ghcr.io/joyjohansson/ci-cd-docker-kubernetes-ansible/my-nginx:${{ env.VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          file: ./path/to/Dockerfile
          push: true
          tags: ghcr.io/joyjohansson/ci-cd-docker-kubernetes-ansible/my-nginx:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install Ansible and Docker modules
        run: |
          pip install ansible
          ansible-galaxy collection install community.docker

      - name: Create inventory from secret
        run: echo "${{ secrets.HOST }}" > inventory

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          echo "Host *\n IdentityFile ~/.ssh/key.pem" > ~/.ssh/config

      - name: Run Ansible Playbook for Nginx Deployment
        run: ansible-playbook -vvv -i inventory ./path/to/nginx-playbook.yml --private-key ~/.ssh/key.pem -u ubuntu
        env:
          IMAGE: "${{ lookup('env', 'IMAGE') }}"
          HOST: "${{ secrets.HOST }}"
          GHCR_USERNAME: "${{ lookup('env', 'USERNAME') }}"
          GHCR_TOKEN: "${{ lookup('env', 'MY_GITHUB_TOKEN') }}"
          REPOSITORY_NAME: "${{ lookup('env', 'REPOSITORY_NAME') }}"

