name: Build and push  Docker Image

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Version from Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Convert Repository Name to Lowercase
        run: echo "REPO_NAME=$(echo '${{ github.repository }}/my-nginx' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker Image
        run: docker build --no-cache -t ghcr.io/$REPO_NAME/my-nginx:$VERSION .

      - name: Test Docker Image
        run: |
          docker run -d --rm -p 8080:80 --name test-nginx ghcr.io/$REPO_NAME/my-nginx:$VERSION
          
          sleep 5
          
          if ! docker ps | grep -q test-nginx; then
            echo "Test failed: Container did not start!"
            exit 1
          fi
          
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Test failed: Nginx did not serve the expected response!"
            exit 1
          fi
          
          echo "Test passed: Nginx is running and serving index.html correctly."
          
          docker stop test-nginx

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/$REPO_NAME/my-nginx:$VERSION

